name: the trader and his lover
favicon: null
layout_spectrum: 0.87536
typography_spectrum: 0.60931
title: 'resourceful, edgy, determined and endlessly surprising interior decorators'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f1e5'
    - '#d1c3a6'
    - '#5b4837'
    - '#060100'
    - '#8c7a62'
  brandStrength: 0.6875
  lightness: 0.6398858861066401
  saturation: 0.5211487100459635
  rhythmicContrast: 0.12826747400686145
purpose: []
